services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file: '.env'
    volumes:
      - ./logs:/usr/src/app/logs
    ports:
      - 5000:5000
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres
    restart: always
    user: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
      POSTGRES_DB: 'metric-tracking'
    expose:
      - 5432
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
